version: '3.1'

services:

  mysql8:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./scripts/mysql/:/docker-entrypoint-initdb.d/
    ports:
      - "13326:3306"

