// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"awesome-bluebook/repository"
	"awesome-bluebook/repository/dao"
	"awesome-bluebook/service"
	"awesome-bluebook/web"
	"github.com/google/wire"
)

// Injectors from wire.go:

func NewUserHandler() *web.UserHandler {
	db := InitDB()
	userDAO := dao.NewGORMUserDAO(db)
	userRepository := repository.NewBasicUserRepository(userDAO)
	logger := InitLogger()
	userService := service.NewBasicUserService(userRepository, logger)
	userHandler := web.NewUserHandler(userService, logger)
	return userHandler
}

// wire.go:

var DBProvider = wire.NewSet(InitDB)

var LoggerProvider = wire.NewSet(InitLogger)

var UserHandlerProvider = wire.NewSet(dao.NewGORMUserDAO, repository.NewBasicUserRepository, service.NewBasicUserService, web.NewUserHandler)
